node-schedule/node-schedule

lib/schedule.js, test/job-test.js
Fix the following tests:
- "Should accept a valid date string" @ date-convenience-methods-test.js
- "Job emits 'scheduled' event with 'run at' Date" @ job-test.js
To fix the first test, support for scheduling date strings has been added to
`Job.schedule`. Also the `DateSpec` function has been removed as it seemed
useless.
=> test: fix failing tests

test/schedule-cron-jobs.js
Using 366 days in a year and 31 days in a month was causing the tests to have 4 assertions instead of just 3.
- Changed days in a month to 29.53 http://en.wikipedia.org/wiki/Month
- Changed days in a year to 365.25 http://en.wikipedia.org/wiki/Year
=> fix failing tests for run job every month and run job every year

test/schedule-cron-jobs.js
- Up to this change, the tests: 'Runs job every month' and 'Runs job every year'
would fail or succeed depending on the date they were run. For example:
running the 'every month' test on "2015-06-01" would fail because the job
would only run twice and not thrice. The reason being that July and August are
both 31 days.
- This commit solves these issues by running these tests in a 4 year period to
be sure the leap year is always taken into account.
=> test: make cron tests more resilient

.eslintrc, lib/increment.js, lib/schedule.js, package.json
Run via ```npm run lint```. I relaxed the default rules a little bit and changed some things to warn only so I didn't have to change too much code to pass the linter. Let me know what you think.
https://github.com/node-schedule/node-schedule/issues/99
=> adds eslint for linting code

.eslintrc, lib/schedule.js
Refactors code to eliminate all lint warnings. Also changed a lint rule so ```while(true)``` doesn't throw a warning.
=> refactor code to eliminate lint warnings and to better follow best practices

package.json
So that it doesn't install eslint everytime the package is installed
=> move eslint to devDependencies

test/job-test.js, test/recurrence-rule-test.js
I noticed that the tests weren't even running the https://github.com/node-schedule/node-schedule/blob/master/lib/schedule.js#L255-261. I also added a test for scheduling a past job, and canceling the next job.
=> increase test coverage for recurrence rule and job

.gitignore, .travis.yml, package.json
Also updates gitignore in case any one runs code coverage reporting locally. As before, please don't merge until I confirm everything is working properly.
=> Integrates coveralls for code coverage reporting

.eslintrc, lib/schedule.js
This change is per https://github.com/node-schedule/node-schedule/pull/112/files#r26470548. There were quite a few single line block statements that had to be updated to pass the linter. See http://eslint.org/docs/rules/curly.html and https://github.com/airbnb/javascript#blocks for some more info on this. Airbnb doesn't seem to address anything but multiline blocks. I also realized that the current linting rules weren't enforcing 2 space indentation, so I added that rule as well.
Let me know what you think.
=> update eslint rules to require all block statements to be wrapped in curly braces

lib/schedule.js
No need to check if it's an object just to check if it is an instanceof
=> Remove unnecessary checks for object

lib/schedule.js
We don't a return false here since the one on line 362 will work just as well.
=> Remove unnecessary return statement

lib/schedule.js
And is already being tracked as an issue. Especially since this is going to have to wait until the next major version to implement. No point in having code that is not being used. In addition, since this method can be hit publicly, it could falsely return true for someone.
=> Remove recurrence validate function since it is not being used

package.json, test/recurrence-rule-test.js
- Adding 1 month from the 31st day of a month that is followed by a less than
31-day month, sets the Date to the first day if the following following month.
For example: if the base Date is the 31st of May, calling addMonth, sets the
date to the 1st of July instead of the 1st of June.
- Fixed by upgrading to cron-parser@0.6.2
- New test added.
=> src: RecurrenceRule bugfix

lib/schedule.js
- As it's already implemented in cron-parser date.js.
=> src: remove unneeded code from nextInvocationDate

.travis.yml, lib/schedule.js, test/convenience-method-test.js, test/job-test.js
I added support for an optional callback to be fired if provided when **job** is completed- just an extension of ``Job``. 
I also wasn't quite sure for the reason of this block:
```javascript
var arg;
for (var i = 0; i < arguments.length; i++) {
arg = arguments[i];
if (typeof arg == 'string' || arg instanceof String) {
name = arg;
} else {
this.job = arg;
}
}
```
Instead of accessing the arguments obj, I just pass in the parameters to the class directly, to allow for more flexibility and removing the loop. If there was a reason, feel free to stop me and explain the method to the madness.
Cheers.
=> Added support for optional callback when scheduled jobs are done

lib/schedule.js, package.json, test/es6/job-test.js, test/job-test.js
This patch adds support for ES6 generators, without introducing any issues for older versions of node that don't support them.
It allows the use case like the following:
```javascript
schedule.scheduleJob('someJob', someDate, function*() {
const record = yield mongoose.model('Foo').findOne(someitem).exec();
doStuffTo(record);
});
```
=> Add support for generators

lib/schedule.js, test/es6/job-test.js, test/job-test.js
If you do something odd like `function*(){}.bind(this)`, the use of `.bind` causes the resultant function to not have a `prototype` property *at all*. ಠ_ಠ
Note I've already incremented the patch version in the `package.json`.
=> Fix generator detection edge case

README.md
This is a **very minor** patch to the README, spurred from my own experience with missing the affected line when making a recurrence rule. My update just draws more attention to that last bit where you explain that if you don't explicitly set the minute value to 0, the job will be executed every minute of the hour.
=> Draws more attention to recurrence rule default values.

lib/schedule.js
This commit gives "breathing room" allowing code to execute while multiple schedule callbacks are called.  nextTick puts something in the current event loop while setImmediate puts something at the top of the next loop iteration.
Test code:
```
var schedule = require('node-schedule');
var util = require('util');
util.log("Scheduling 5000 crons");
for (var i = 0; i < 5000; i++) {
schedule.scheduleJob('00 45 13 * * *', function(){
});
}
util.log("Ok");
var p = new Date().getTime();
setInterval(function () {
p = p + 1000;
var difference = new Date().getTime() - p;
util.log("Difference between expected & actual: " + difference)
}, 1000);
```
RESULTS BEFORE:
```
5000 crons fire @1:30:00 (process.nextTick)
23 Feb 13:28:57 - Difference between expected & actual: 270
23 Feb 13:28:58 - Difference …
```
=> Change nextTick to setImmediate for schedule callbacks

lib/schedule.js, test/recurrence-rule-test.js
Avoid an infinite loop by checking if we're past the year set in the
RecurrenceRule.
=> src: fix scheduling with RR with year property set

lib/schedule.js, package.json
Using `sorted-array-functions` to sort the invocation arrays, improve
the module performance greatly when scheduling lots (thousands) of jobs.
Fixes: https://github.com/node-schedule/node-schedule/issues/333
=> src: improve performance when sorting invocations

README.md, lib/schedule.js, test/job-test.js
Previously, if a job was invoked and caused an error, it would cause an unhandled exception or an unhandled promise rejection. The only way for a user to handle it was to wrap the actual job in a wrapper function.
This makes it easier to handle by catching the error and emitting an `error` event when an error is thrown or a rejected Promise is a returned.
As a bonus, the result of the job is returned when `job.invoke()` is called.
Fixes #389.
=> Emit `error` events

README.md
Saw timezone support has been added to node-schedule finally but the readme doesn't seem to reflect that. Hoping this might make it a bit more clear
=> Added tz rule to readme

UPGRADING.md, lib/schedule.js, test/convenience-method-test.js
This removes support for passing job objects with an `execute()` method instead of a function.
This reverts e7c475f (#57).
Fixes #183 (see #220).
This is technically a breaking change, although this "feature" was never documented.
=> Remove support for job objects

README.md, lib/Invocation.js, test/job-test.js
Dear Developers & Maintainers, first of all thanks a lot for this package, it proved itself very useful in my daily projects! I stumbled upon a use case which I could not cover using the currently available API. I therefore would like to propose a new feature consisting of an additional `success` event.
I came across a situation where we need to track the number of consecutive failed invocations. Therefore, it would be helpful to not only be aware of failed job invocations, but also successful ones. This allows us to reset the internal counter of consecutive failures. 
When the callback of a job invocation returns successfully (i.e. returning without raising an error), a `success` event is emitted receiving the data returned by the callback. In case of the callback returning a promise, …
=> Emit a success event after a successful job invocation.

README.md
The documentation for [Recurrence Rule Scheduling](https://github.com/node-schedule/node-schedule#recurrence-rule-scheduling) implies that the code will be run every day at exactly midnight, once.
```javascript
const rule = new schedule.RecurrenceRule();
rule.hour = 0;
rule.tz = 'Etc/UTC';
const job = schedule.scheduleJob(rule, function(){
console.log('A new day has begun in the UTC timezone!');
});
```
It later says in a quote
> If we did not explicitly set minute to 0 above, the message would have instead been logged at 5:00pm, 5:01pm, 5:02pm, ..., 5:59pm. Probably not what you want.
I made the mistake of not reading this, and I think many others (#498) could also make the same mistake. Depending on the computation within the schedule function, this could be costly!
This PR updates the …
=> Add missing minute to timezone RecurrenceRule example
